# Name des Workflows
name: Build & Test Blog-Example

# Auslöser für den Build sind ein push nach master bzw.
# ein Pull Request wird nach master gemerged
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Definition des Build Jobs
jobs:
  build:
    # Wir werden unseren Job auf der aktuellsten Version von Ubuntu ausführen
    runs-on: ubuntu-latest

    # Außerdem werden wir die Tests mit der NodeJS Version 10 ausführen
    strategy:
      matrix:
        node-version: [10.x]

    # Hier werden die einzelnen Schritte definiert
    steps:
      # Zunächst wird die aktuellste Version des Repositories heruntergeladen
    - uses: actions/checkout@v2
      # Zum besseren Verständnis wird der Name sowie die NodeJS version ausgegeben
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      # Hier können wir nun direkt die Befehle angeben welche ausgeführt werden sollten
      # Diese Befehle gleichen den Befehlen welche wir lokal im Terminal angeben

      # Versetzt npm in den Continous Integration Modus
    - run: npm ci
      # Erstellt / Transpiliert die Anwendung
    - run: npm run build
      # Prüft auf einhalten der Code Format Regeln
    - run: npm run lint
      # Führt die Unit, Layout und Integrationstests aus
    - run: npm run run-tests
